name: Run Unit Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: build and start
        run: |
          yarn install
          yarn build
        env:
          CI: true
      - name: Unit Tests
        run: |
          yarn test
        env:
          CI: true
